from Tkinter import *
import sqlite3
con=sqlite3.Connection('Thumbs')
cur=con.cursor()
cur.execute("create table if not exists customer(name varchar(20) primary key,service varchar(100))")
root=Tk()
root.configure(bg='#3dc0cc')
Label(root,text='SEMESTER-3',font='Arial 10 bold',bg='#3dc0cc',fg='red4').grid(row=0,column=0,stick=W)
Label(root,text='PYTHON PROJECT',font='broadway 15 bold',bg='#3dc0cc').grid(row=1,column=0)
Label(root,text='ADVENTURE SPORTS',font='Algerian 25 bold',bg='#3dc0cc',fg='red2').grid(row=2,column=0)
Label(root,text='PRANJAL SAKARGAYAN',font='CASTELLAR 15 bold',bg='#3dc0cc').grid(row=4,column=0)
Label(root,text='161B147',font='CASTELLAR 15 bold',bg='#3dc0cc').grid(row=5,column=0)
Label(root,text='B5 BATCH',font=' CASTELLAR 15 bold',bg='#3dc0cc').grid(row=6,column=0)
Label(root,text='ARE YOU READY!!! for your next adventure trip with "CRAZY FOR ADVENTURE" friends!!!',font='Chiller 20 bold',bg='#3dc0cc',fg='blue2').grid(row=10,column=0)
def proceed():
  root.destroy()
  root1=Tk()
  root1.configure(bg='#1973c1')
  root1.title("GOA TOURISM")
  Label(root1,text='GET SET GO!',font='georgia 30 bold',bg='LIGHT GREEN',fg='gray7').grid(row=0,column=0,sticky=E+W+S+N)
  a=PhotoImage(file="beach11.gif")
  Label(root1,image=a).grid(row=1,column=0)
  def go():
    root1.destroy()
    root2=Tk()
    root2.configure(bg='#1973c1')
    root2.title("GOA TOURISM-ADVENTURE SPORTS")
    Label(root2,text='LIST OF SPORTS',font='georgia 30 bold',bg='#1973c1').grid(row=0,column=0)
    v=IntVar()
    def trek():
        root3=Tk()
        root3.configure(bg='salmon')
        root3.title('ADVENTURE SPORT-TREKKING')
        root3.configure(bg='plum1')
        #a=PhotoImage(file="trekking.gif")
        #Label(root3,image=a).grid(row=1,column=0)
        Label(root3,text='Planning a Goa trip with only the beaches and party in mind,\n is a grave mistake as it offers some of the most enthralling terrains for trekking. ',font='Arial 15',bg='OliveDrab2').grid(row=1,column=0)
        
        def check():
             Label(root3,text='Rs.'+str(v.get()),font='Arial 10 bold',bg='salmon').grid(row=3,column=0)
        Button(root3,text='check',font='jokerman 20 bold',command=check).grid(row=2,column=0)
        def back():
             
             root3.destroy()
                
        Button(root3,text='BACK',command=back).grid(row=4,column=1,sticky=E)
        def ok():
             root3.destroy() 
             import tkMessageBox
             ok=Tk()
             ok.configure(bg='salmon')
             ok.title('ADVENTURE SPORTS')
             Label(ok,text='FILL DETAILS',font='Arial 25 bold',bg='salmon').grid(row=0,column=0,sticky=E+W+S+N)
             Label(ok,text='NAME:',font ='Arial 15 bold',bg='salmon').grid(row=1,column=0)
             e=Entry(ok)
             e.grid(row=1,column=1)
             Label(ok,text='CARD NO',font='Arial 15 bold',bg='salmon').grid(row=2,column=0)
             f=Entry(ok)
             f.grid(row=2,column=1)
             Label(ok,text='OTP',font='Arial 15 bold',bg='salmon').grid(row=3,column=0)
             g=Entry(ok)
             g.grid(row=3,column=1)
             def clears():
                 e.delete(0,END)
                 f.delete(0,END) 
             def pay():
                 Label(ok,text=' OTP Applied  !!!',bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                 Label(ok,text=' Enjoy your trip  '+str(e.get()),bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                 tkMessageBox.showinfo('transaction ','transaction complete!!!!')
                 clears()
             def ex():
                 ok.destroy()
             Button(ok,text='PAY',command=pay).grid(row=4,column=0)
             Button(ok,text='EXIT',command=ex).grid(row=4,column=1)
             mainloop()
        Button(root3,text='OK',command=ok).grid(row=4,column=0,sticky=W)     
        mainloop()
    Radiobutton(root2,text='TREKKING',font='georgia 15 bold',variable=v,value=2650,bg='#1973c1',command=trek,fg='gray7').grid(row=1,column=0)
    def ATV():
             root4=Tk()
             root4.configure(bg='salmon')
             root4.title('ADVENTURE SPORT-ATV biking')
    #c=PhotoImage(trekking.gif)
    #Label(root3,image=c).grid(row=0,column=0)
             Label(root4,text='ATV biking is an exceptionally thrilling activity, where in you can ride \n an extremely powered bike in all the types of terrains. Be it on rocks, woods or muds, it will surely provide you with a lot of fun and enthrallment.\n Quad biking in Goa helps you experience all of these! ',font='Arial 15',bg='OliveDrab2').grid(row=0,column=0)
             def check():
                  Label(root4,text='Rs.'+str(v.get()),font='Arial 10 bold',bg='salmon').grid(row=3,column=0)
             Button(root4,text='check',font='jokerman 20 bold',command=check).grid(row=2,column=0)
             def back():
                     root4.destroy()
             Button(root4,text='BACK',command=back).grid(row=4,column=1,sticky=E)
             def ok():
                 root4.destroy() 
                 import tkMessageBox
                 ok=Tk()
                 ok.configure(bg='salmon')
                 ok.title('ADVENTURE SPORTS')
                 Label(ok,text='FILL DETAILS',font='Arial 25 bold',bg='salmon').grid(row=0,column=0)
                 Label(ok,text='Name:',font ='Arial 15 bold',bg='salmon').grid(row=1,column=0)
                 e=Entry(ok)
                 e.grid(row=1,column=1)
                 Label(ok,text='CARD NO : ',font='Arial 15 bold',bg='salmon').grid(row=2,column=0)
                 f=Entry(ok)
                 f.grid(row=2,column=1)
                 Label(ok,text='OTP : ',font='Arial 15 bold',bg='salmon').grid(row=3,column=0)
                 g=Entry(ok)
                 g.grid(row=3,column=1)
                 def clears():
                      e.delete(0,END)
                      f.delete(0,END)
                 def pay():
                      Label(ok,text=' OTP Applied  !!!',bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      Label(ok,text=' Enjoy your trip  '+str(e.get()),bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      tkMessageBox.showinfo('transaction ','transaction complete!!!!')
                      clears()
                 def ex():
                     ok.destroy()
                 Button(ok,text='PAY',command=pay).grid(row=4,column=0)
                 Button(ok,text='EXIT',command=ex).grid(row=4,column=1)
                 mainloop()
             Button(root4,text='OK',command=ok).grid(row=4,column=0,sticky=W)     
             mainloop()
    Radiobutton(root2,text='ATV BIKING',font='georgia 15 bold',variable=v,value=500,bg='#1973c1',command=ATV,fg='gray7').grid(row=2,column=0)
    def Airballoon():
              root5=Tk()
              root5.configure(bg='salmon')
              root5.title('ADVENTURE SPORT-HOT AIR BALLOON')
    #c=PhotoImage(trekking.gif)
    #Label(root3,image=c).grid(row=0,column=0)
              Label(root5,text='If you are done with exploring the coastal beauty of Goa, \nthen\n, embark on this amazing Hot Air Ballooning adventure in South Goa. ',font='Arial 15',bg='OliveDrab2').grid(row=0,column=0)
              def check():
                   Label(root5,text='Rs.'+str(v.get()),font='Arial 10 bold',bg='salmon').grid(row=3,column=0)
              Button(root5,text='check',font='jokerman 20 bold',command=check).grid(row=2,column=0)
              def back():
                     root5.destroy()
              Button(root5,text='BACK',command=back).grid(row=4,column=1,sticky=E)
              def ok():
                 root5.destroy() 
                 import tkMessageBox
                 ok=Tk()
                 ok.configure(bg='salmon')
                 ok.title('ADVENTURE SPORTS')
                 Label(ok,text='FILL DETAILS',font='Arial 25 bold',bg='salmon').grid(row=0,column=0)
                 Label(ok,text='Name:',font ='Arial 15 bold',bg='salmon').grid(row=1,column=0)
                 e=Entry(ok)
                 e.grid(row=1,column=1)
                 Label(ok,text='CARD NO',font='Arial 15 bold',bg='salmon').grid(row=2,column=0)
                 f=Entry(ok)
                 f.grid(row=2,column=1)
                 Label(ok,text='OTP : ',font='Arial 15 bold',bg='salmon').grid(row=3,column=0)
                 g=Entry(ok)
                 g.grid(row=3,column=1)
                 def clears():
                      e.delete(0,END)
                      f.delete(0,END)
                 def pay():
                      Label(ok,text=' OTP Applied  !!!',bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      Label(ok,text=' Enjoy your trip  '+str(e.get()),bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      tkMessageBox.showinfo('transaction ','transaction complete!!!!')
                      clears()
                 def ex():
                     ok.destroy()
                                 
                 Button(ok,text='PAY',command=pay).grid(row=4,column=0)
                 Button(ok,text='EXIT',command=ex).grid(row=4,column=1)
                 mainloop()
              Button(root5,text='OK',command=ok).grid(row=4,column=0,sticky=W)     
              mainloop()
    Radiobutton(root2,text='HOT AIR BALLOON FLIGHT IN ASSOLDA GROUND',font='georgia 15 bold',variable=v,value=8000,bg='#1973c1',command=Airballoon,fg='gray7').grid(row=3,column=0)
    def watersports():
               root6=Toplevel()
               root6.configure(bg='salmon')
               root6.title('ADVENTURE SPORT-WATER SPORTS')
               Label(root6,text='A trip to Goa can never be complete with enjoying water sports! \nOne of the best hubs for water sports in the country, the beaches and \nthe waterfronts of Goa make it for an international water sports destination. ',font='Arial 15',bg='OliveDrab2').grid(row=0,column=0)
               def check():
                    Label(root6,text='Rs.'+str(v.get()),font='Arial 10 bold',bg='salmon').grid(row=3,column=0)
               Button(root6,text='check',font='jokerman 20 bold',command=check).grid(row=2,column=0)
               def back():
                     root6.destroy()
               Button(root6,text='BACK',command=back).grid(row=4,column=1,sticky=E)
               def ok():
                 root6.destroy() 
                 import tkMessageBox
                 ok=Tk()
                 ok.configure(bg='salmon')
                 Label(ok,text='FILL DETAILS',font='Arial 25 bold',bg='salmon').grid(row=0,column=0)
                 Label(ok,text='Name:',font ='Arial 15 bold',bg='salmon').grid(row=1,column=0)
                 e=Entry(ok)
                 e.grid(row=1,column=1)
                 Label(ok,text='CARD NO',font='Arial 15 bold',bg='salmon').grid(row=2,column=0)
                 f=Entry(ok)
                 f.grid(row=2,column=1)
                 Label(ok,text='OTP : ',font='Arial 15 bold',bg='salmon').grid(row=3,column=0)
                 g=Entry(ok)
                 g.grid(row=3,column=1)
                 def clears():
                      e.delete(0,END)
                      f.delete(0,END)
                 def pay():
                      Label(ok,text=' OTP Applied  !!!',bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      Label(ok,text=' Enjoy your trip  '+str(e.get()),bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      tkMessageBox.showinfo('transaction ','transaction complete!!!!')
                      clears()
                 def ex():
                     ok.destroy()
                 Button(ok,text='PAY',command=pay).grid(row=4,column=0)
                 Button(ok,text='EXIT',command=ex).grid(row=4,column=1)
                 mainloop()
               Button(root6,text='OK',command=ok).grid(row=4,column=0,sticky=W)     
               mainloop()
    Radiobutton(root2,text='WATER SPORTS',font='georgia 15 bold',variable=v,value=2070,bg='#1973c1',command=watersports,fg='gray7').grid(row=4,column=0)
    def camping():
                root7=Tk()
                root7.configure(bg='salmon')
                root7.title('ADVENTURE SPORT-CAMPING')
    #c=PhotoImage(trekking.gif)
    #Label(root3,image=c).grid(row=0,column=0)
                Label(root7,text=' Camping in Goa has its own fun, delight and excitement. One of the best \namongst these locations is located on the south side of Palolem beach.',font='Arial 15',bg='OliveDrab2').grid(row=0,column=0)
                def check():
                     Label(root7,text='Rs.'+str(v.get()),font='Arial 10 bold',bg='salmon').grid(row=3,column=0)
                Button(root7,text='check',font='jokerman 20 bold',command=check).grid(row=2,column=0)
                def back():
                     root7.destroy()
                Button(root7,text='BACK',command=back).grid(row=4,column=1,sticky=E)
                def ok():
                 root7.destroy() 
                 import tkMessageBox
                 ok=Tk()
                 ok.configure(bg='salmon')
                 ok.title('ADVENTURE SPORTS')
                 Label(ok,text='FILL DETAILS',font='Arial 25 bold',bg='salmon').grid(row=0,column=0)
                 Label(ok,text='Name:',font ='Arial 15 bold',bg='salmon').grid(row=1,column=0)
                 e=Entry(ok)
                 e.grid(row=1,column=1)
                 Label(ok,text='CARD NO',font='Arial 15 bold',bg='salmon').grid(row=2,column=0)
                 f=Entry(ok)
                 f.grid(row=2,column=1)
                 Label(ok,text='OTP : ',font='Arial 15 bold',bg='salmon').grid(row=3,column=0)
                 g=Entry(ok)
                 g.grid(row=3,column=1)
                 def clears():
                      e.delete(0,END)
                      f.delete(0,END)
                 def pay():
                      Label(ok,text=' OTP Applied  !!!',bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      Label(ok,text=' Enjoy your trip  '+str(e.get()),bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      tkMessageBox.showinfo('transaction ','transaction complete!!!!')
                      clears()
                 def ex():
                     ok.destroy()
                 Button(ok,text='PAY',command=pay).grid(row=4,column=0)
                 Button(ok,text='EXIT',command=ex).grid(row=4,column=1)
                Button(root7,text='OK',command=ok).grid(row=4,column=0,sticky=W)
                mainloop()
    Radiobutton(root2,text='CAMPING',font='georgia 15 bold',variable=v,value=4900,bg='#1973c1',command=camping,fg='gray7').grid(row=5,column=0)
    def scubadiving():
                 root8=Tk()
                 root8.configure(bg='salmon')
                 root8.title('ADVENTURE SPORT-SCUBA DIVING')
    #c=PhotoImage(trekking.gif)
    #Label(root3,image=c).grid(row=0,column=0)
                 Label(root8,text='Gear up from head to toe for a diving experience \nup to 12 meters and experience the beauty of deep undersea life. ',font='Arial 15',bg='OliveDrab2').grid(row=0,column=0)
                 def check():
                      Label(root8,text='Rs.'+str(v.get()),font='Arial 10 bold',bg='salmon').grid(row=3,column=0)
                 Button(root8,text='check',font='jokerman 20 bold',command=check).grid(row=2,column=0)
                 def back():
                     root8.destroy()
                 Button(root8,text='BACK',command=back).grid(row=4,column=1,sticky=E)
                 def ok():
                   root8.destroy() 
                   import tkMessageBox
                   ok=Tk()
                   ok.configure(bg='salmon')
                   ok.title('ADVENTURE SPORTS')
                   Label(ok,text='FILL DETAILS',font='Arial 25 bold',bg='salmon').grid(row=0,column=0)
                   Label(ok,text='Name:',font ='Arial 15 bold',bg='salmon').grid(row=1,column=0)
                   e=Entry(ok)
                   e.grid(row=1,column=1)
                   Label(ok,text='CARD NO',font='Arial 15 bold',bg='salmon').grid(row=2,column=0)
                   f=Entry(ok)
                   f.grid(row=2,column=1)
                   Label(ok,text='OTP : ',font='Arial 15 bold',bg='salmon').grid(row=3,column=0)
                   g=Entry(ok)
                   g.grid(row=3,column=1)
                 def clears():
                      e.delete(0,END)
                      f.delete(0,END)
                 def pay():
                      Label(ok,text=' OTP Applied  !!!',bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      Label(ok,text=' Enjoy your trip  '+str(e.get()),bg='salmon',font='georgia 15 bold').grid(row=4,column=0)
                      tkMessageBox.showinfo('transaction ','transaction complete!!!!')
                      clears()
                 def ex():
                     ok.destroy()
                                 
                     Button(ok,text='PAY',command=pay).grid(row=4,column=0)
                     Button(ok,text='EXIT',command=ex).grid(row=4,column=1)
                     mainloop()
                 Button(root8,text='OK',command=ok).grid(row=4,column=0,sticky=W)     
                 mainloop()
    Radiobutton(root2,text='SCUBA DIVING AT GRANDE ISLAND ',font='georgia 15 bold',variable=v,value=5000,bg='#1973c1',command=scubadiving,fg='gray7').grid(row=6,column=0)
    def done():
            root2.destroy()
    Button(root2,text='DONE',font='jokerman 15 bold',command=done).grid(row=7,column=0) 
    mainloop()

  Button(root1,text='GO',font='jokerman 20 bold',command=go).grid(row=2,column=0)
  mainloop()
Button(root,text='LETS  PROCEED',font='jokerman',command=proceed).grid(row=11,column=0)
mainloop()
